<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="tst_ExpectFail" timestamp="@TEST_START_TIME@" hostname="@HOSTNAME@" tests="24" failures="6" errors="0" skipped="0" time="@TEST_DURATION@">
  <properties>
    <property name="QTestVersion" value="@INSERT_QT_VERSION_HERE@"/>
    <property name="QtVersion" value="@INSERT_QT_VERSION_HERE@"/>
    <property name="QtBuild" value=""/>
  </properties>
  <testcase name="initTestCase" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xfailAndContinue" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[begin]]>
      <![CDATA[This should xfail]]>
      <![CDATA[after]]>
    </system-out>
  </testcase>
  <testcase name="xfailAndAbort" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[begin]]>
      <![CDATA[This should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailTwice" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <failure type="fail" message="Already expecting a fail"/>
  </testcase>
  <testcase name="xfailWithQString" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[A string]]>
      <![CDATA[Bug 5 (The message)]]>
    </system-out>
  </testcase>
  <testcase name="xfailDataDrivenWithQVerify(Pass 1)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xfailDataDrivenWithQVerify(Pass 2)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xfailDataDrivenWithQVerify(Abort)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[This test should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailDataDrivenWithQVerify(Continue)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[This test should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailDataDrivenWithQCompare(Pass 1)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xfailDataDrivenWithQCompare(Pass 2)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xfailDataDrivenWithQCompare(Abort)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[This test should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailDataDrivenWithQCompare(Continue)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[This test should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailOnWrongRow(right row)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xfailOnAnyRow(first row)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[This test should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailOnAnyRow(second row)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <system-out>
      <![CDATA[This test should xfail]]>
    </system-out>
  </testcase>
  <testcase name="xfailWithoutVerify(first row)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <failure type="fail" message="QEXPECT_FAIL was called without any subsequent verification statements"/>
  </testcase>
  <testcase name="xfailWithoutVerify(second row)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <failure type="fail" message="QEXPECT_FAIL was called without any subsequent verification statements"/>
  </testcase>
  <testcase name="xpass" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <failure type="xpass" message="&apos;true&apos; returned TRUE unexpectedly. ()"/>
  </testcase>
  <testcase name="xpassDataDrivenWithQVerify(XPass)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <failure type="xpass" message="&apos;true&apos; returned TRUE unexpectedly. ()"/>
  </testcase>
  <testcase name="xpassDataDrivenWithQVerify(Pass)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="xpassDataDrivenWithQCompare(XPass)" classname="tst_ExpectFail" time="@TEST_DURATION@">
    <failure type="xpass" message="QCOMPARE(1, 1) returned TRUE unexpectedly."/>
  </testcase>
  <testcase name="xpassDataDrivenWithQCompare(Pass)" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
  <testcase name="cleanupTestCase" classname="tst_ExpectFail" time="@TEST_DURATION@"/>
</testsuite>
